---
title: "Practica2"
output:
  html_document: default
  pdf_document: default
date: "2023-04-23"
---


## Pregunta 1.1

```{r}
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)
library(ggpubr)
library(httr)
library(XML)
library(ggpubr)
library(tensorflow)


url <- "https://www.mediawiki.org/wiki/MediaWiki"


page <- GET(url)


status_code(page)

parsed_page <- htmlParse(content(page, as = "text"))
```




## Pregunta 1.2
```{r}


title <- xpathSApply(parsed_page, "//title", xmlValue)
title


stylesheets <- xpathSApply(parsed_page, "//link[@rel='stylesheet']/@href")
stylesheets

author <- xpathSApply(parsed_page, "//meta[@name='author']/@content")
author


description <- xpathSApply(parsed_page, "//meta[@name='description']/@content")
description

encoding <- xpathSApply(parsed_page, "//meta[@charset]/@charset")
encoding


keywords <- xpathSApply(parsed_page, "//meta[@name='keywords']/@content")
keywords



```



## Pregunta 1.3

```{r}

links_text <- xpathSApply(parsed_page, "//a", xmlValue)
print(links_text)


links_url <- xpathSApply(parsed_page, "//a", xmlGetAttr, 'href')
print(links_url)
```
 

## Pregunta 1.4 & 1.5
 
 
```{r}
tabla <- data.frame(links_text = character(),
                    links_original_url = character(),
                    links_url = character(),
                    links_relative = character(),
                    links_internal = character(),
                    repeticiones = numeric(),
                    scraps = character(),
                    stringsAsFactors = FALSE)

frecuencia <- table(links_url)

for (i in 1:length(links_text)) {
  Sys.sleep(2)
  print("round done")
  tabla[i, "links_text"] <- links_text[i]
  tabla[i, "links_original_url"] <- links_url[i]
  tabla[i, "links_url"] <- links_url[i]
  tabla[i, "links_relative"] <- "N"
  tabla[i, "links_internal"] <- "S"
  tabla[i, "repeticiones"] <- frecuencia[links_url[i]]
  

  validation_wiki <- startsWith(links_url[i], "/wiki/")
  if(validation_wiki) {
    tabla[i, "links_url"] <- paste0("https://www.mediawiki.org", links_url[i])
    tabla[i, "links_relative"] <- "S"
  }
  
  
  validation_https <- startsWith(links_url[i], "https:")
  if(validation_https) {
    tabla[i, "links_url"] <- links_url[i]
    validation_internal <- startsWith(links_url[i], "https://www.mediawiki.org")
    if(!validation_internal) {
      tabla[i, "links_internal"] <- "N"
    }
  }
  
  validation_slash <- startsWith(links_url[i], "//")
  if(validation_slash) {
    tabla[i, "links_url"] <- paste0("https:", links_url[i])
    tabla[i, "links_relative"] <- "S"
  }
  
  validation_w <- startsWith(links_url[i], "/w/")
  if(validation_w) {
    tabla[i, "links_url"] <- paste0("https://www.mediawiki.org", links_url[i])
    tabla[i, "links_relative"] <- "S"
  }
  
  validation_hash <- startsWith(links_url[i], "#")
  if(validation_hash) {
    tabla[i, "links_url"] <- paste0("https://www.mediawiki.org/wiki/MediaWiki", links_url[i])
    tabla[i, "links_relative"] <- "S"
  }
  
  print(paste0("TEST> " , links_url[i]))
  
  code <- status_code(HEAD(tabla[i, "links_url"]))
  tabla[i, "scraps"] <- code
  print(code)
}


```
 
 
 
 
## Pregunta 2.1 & 2.2

```{r}
library(ggplot2)
library(ggpubr)

relative <- c(1, 2, 3, 4, 5, 4, 3, 2, 1)
no_relative <- c(2, 4, 6, 8, 10, 8, 6, 4, 2)

tabla2 <- tabla[tabla$links_relative =="S", c("repeticiones")]
tabla3 <- tabla[tabla$links_relative =="N", c("repeticiones")]
tabla6 <- tabla[TRUE, c("links_internal")]
tabla7 <- as.numeric(tabla[TRUE, c("scraps")])
tabla7 <- (tabla[TRUE, c("scraps")])


relative <- tabla2
no_relative <- tabla3


p1 <- ggplot(data.frame(x=relative), aes(x=x)) + 
  geom_histogram(aes(y=..count..), fill="blue", alpha=0.5) +
  labs(title="Histograma de relative", x="Valores", y="Frecuencia") 

p2 <- ggplot(data.frame(x=no_relative), aes(x=x)) + 
  geom_histogram(aes(y=..count..), fill="red", alpha=0.5) +
  labs(title="Histograma de no-relative", x="Valores", y="Frecuencia")

factor_tabla6 <- factor(tabla6, levels = c("S", "N"))

data <- data.frame(x = factor_tabla6)

p3 <- ggplot(data, aes(x = x)) + 
  geom_bar(aes(y=..count../sum(..count..)), fill="blue", alpha=0.5, stat = "count") +
  labs(title="Histograma de tabla6", x="Valores", y="Frecuencia")

theme_set(theme_classic())

ggarrange(p1, p2, p3, ncol=1, heights=c(1,1,1.2))



```


## Pregunta 2.3


```{r}

relative <- tabla2
no_relative <- tabla3

p1 <- ggplot(data.frame(x=relative), aes(x=x)) + 
  geom_histogram(aes(y=..count..), fill="blue", alpha=0.5) +
  labs(title="Histograma de relative", x="Valores", y="Frecuencia") 

p2 <- ggplot(data.frame(x=no_relative), aes(x=x)) + 
  geom_histogram(aes(y=..count..), fill="red", alpha=0.5) +
  labs(title="Histograma de no-relative", x="Valores", y="Frecuencia")

factor_tabla6 <- factor(tabla6, levels = c("S", "N"))

data <- data.frame(x = factor_tabla6)

p3 <- ggplot(data, aes(x = x)) + 
  geom_bar(aes(y=..count../sum(..count..)), fill="blue", alpha=0.5, stat = "count") +
  labs(title="Histograma de tabla6", x="Valores", y="Frecuencia")

p4 <- ggplot(data.frame(x=tabla7), aes(x= "", fill = x)) + 
  geom_bar(width = 1) + coord_polar(theta = "y") +
  labs(title="status code")

theme_set(theme_classic())

ggarrange(p1, p2, p3, p4, ncol=1, heights=c(1,1,1,1.2))





cod_freq <- table(tabla$scraps)

value_percent <- round(prop.table(cod_freq) * 100, 2)
value_percent <- as.numeric(value_percent)
code_full <- data.frame(code_status = names(cod_freq),
                        frequency = as.numeric(cod_freq),
                        percentage = value_percent)








chart_graphic <- ggplot(code_full, aes(x="", y=percentage, fill=code_status)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) +
  ggtitle("Pie chart") +
  theme_void() +
  geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust = 0.5), size = 3)

# mixeando graficas
grid.arrange(histogram, bar_graphic, chart_graphic, ncol=3)

 
 
```
 
 
 
 